spring:
  datasource:
    url: ec2-79-125-26-232.eu-west-1.compute.amazonaws.com
    username: d1ssufbjh9j8ps
    password: kunjqrrsnixtrk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual-creation: true
server:
  port: 9999